# Se especifica la versión de la sintaxis del archivo de CloudFormation
AWSTemplateFormatVersion: "2010-09-09"
Description: "Prueba IRIS"

# Definición de parámetros personalizados para el nombre de la clave SSH
# y la IP para el acceso
Parameters:
  KeySSH:
    Description: "Ingrese el nombre de la clave SSH que se creara y asociara a la instancia"
    Type: String
    Default: EC2Key

  AllowedIP:
    Description: "Ingrese la direccion IP desde la que se permitira el acceso SSH "
    Type: String

Resources:
  # Se crea la clave SSH y se le asigna el nombre obtenido por el usuario,
  # o por defecto se usará "EC2Key"
  EC2KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref KeySSH

  # Se crea un grupo de seguridad para establecer el protocolo de comunicación,
  # puerto e IP permitida.
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Acceso SSH desde una IP especifica"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedIP

  # Se crea el recurso EC2 con los parametos requeridos
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      AvailabilityZone: us-east-1a
      KeyName: !Ref EC2KeyPair
      ImageId: ami-0a0e5d9c7acc336f1
      SecurityGroupIds:
        - !Ref SecurityGroup

Outputs:
  InstanceId:
    Description: "ID de la instancia EC2 creada"
    Value: !Ref EC2Instance
  ClaveSSH:
    Description: "La private Key se encuentra en el parameter store"
    Value: "La private Key se encuentra en el parameter store"
