name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Give execution permissions to the script
        run: chmod +x hello.sh

      - name: Run Hello World script
        run: ./hello.sh

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Lint Bash scripts
        run: shellcheck hello.sh
