name: CI Pipeline

# Activar el pipeline en cada push a la rama main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Comprobar el código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Ejecutar el script que imprime "Hello, World!"
      - name: Run Hello World script
        run: echo "Hello, World!"

      # Validar el código con un linter (en este caso, ShellCheck)
      - name: Lint Bash scripts
        run: |
          if command -v shellcheck > /dev/null 2>&1; then
            shellcheck *.sh
          else
            echo "ShellCheck is not installed."
          fi
